### PR TITLE
Added support for Laravel 8

### PR DESCRIPTION
**Pull request by CasperBE**

### CODE REVIEW

**Comment by nickurt** [comment]
Hi, can you update the github actions file aswell?

**Comment by CasperBE** [comment]
Sure! I've updated the github actions file. No experience with this file so I hope all goes well.

**Comment by CasperBE** [comment]
Seems like I have difficulties trying to push the change on the github actions file
_refusing to allow an OAuth App to create or update workflow `.github/workflows/run-tests.yml` without `workflow` scope_
I have to find out how I can solve this first

**Comment by CasperBE** [comment]
The actions file got updated, all tests passed 🤗

**Comment by nickurt** [comment]
Thanks

**Pull request merged**
